# Generated by Django 3.0.3 on 2020-08-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('director', models.CharField(max_length=250)),
                ('starring', models.CharField(max_length=300)),
                ('Plot', models.TextField()),
                ('release', models.DateField()),
                ('status', models.CharField(choices=[('released', 'Released'), ('upcoming', 'Upcoming')], max_length=10)),
            ],
        ),
    ]
