# Generated by Django 3.0.3 on 2020-08-28 07:40

import Movie.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0002_movie_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(null=True, upload_to=Movie.models.fileuplaod),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('Released', 'Released'), ('Coming', 'Upcoming')], max_length=10),
        ),
    ]
