# Generated by Django 3.0.3 on 2020-08-28 10:30

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('Movie', '0003_auto_20200828_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tag',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
