# Generated by Django 3.0.3 on 2020-09-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0006_movie_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='starring',
            field=models.CharField(max_length=500),
        ),
    ]
