# Generated by Django 3.0.3 on 2020-09-12 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0007_auto_20200909_0753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('-rating',)},
        ),
    ]
